### ISSUE TITLE
Add support for parsing MS Word docs

### ISSUE THREAD

**Issue by apetov** [apetov/phoneparser-js#5]
There are lots of existing open source projects that can help parse a Word doc into Text, which can then be parsed by your earlier code

**Comment by ohodovaniuk1** [comment]
Hey Jean,
I just want to leave a note that i am currently working on the fix to support MS doc and i will push the solution soon.

**Comment by apetov** [comment]
@ohodovaniuk1 Thanks for your contribution! I've merged everything.
17d3827
